version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: db-container
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3

  app:
    build: ./backend/src
    container_name: app-container
    ports:
      -  ${APP_PORT}:${APP_PORT}
      #- "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_PORT: ${POSTGRES_PORT}
      DB_HOST: ${POSTGRES_HOST}
      APP_ENV: ${APP_ENV}

  web:
    build: ./web
    container_name: web-container
    ports:
      - ${WEB_PORT}:${WEB_PORT}
      #- "8501:8501"
    environment:
      WEB_BASE_URL: ${WEB_BASE_URL}
    # volumes:
    #   - .:/app
    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres-data: